server.port=${SERVER_PORT}

# setup database
spring.datasource.url=${URL_DATABASE}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASS_DB}

#  Hibernate
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
