spring.application.name=chat-app
server.port=${SERVER_PORT}

# Database configuration
spring.datasource.url=${URL_DATABASE}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASS_DB}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SHOW_SQL}
